project:
  name: baseline
models:
  backend: hf
  target_model: meta-llama/Llama-3.2-1B-Instruct
  load_4bit: true
  device_map: auto
  max_new_tokens: 128
  temperature: 0.7
  top_p: 0.95
  red_model: meta-llama/Llama-3.2-1B-Instruct
data:
  seeds_file: data/seeds/basic.jsonl
train:
  iterations: 2
  seeds_per_iter: 100
validation:
  enabled: true
  seeds_file: data/dna/dna_seeds.jsonl
  max_per_iter: 300
report:
  save_unmasked: true
costs:
  openai:
    gpt-4o-mini:
      input_per_1k: 0.15
      output_per_1k: 0.6
  hf_default:
    input_per_1k: 0.0
    output_per_1k: 0.0
run:
  rng_seed: 7
  iters: 2
  seeds: 100
  run_name: ''
  iterations: 2
  seeds_per_iter: 100
  output_dir: /content/drive/MyDrive/llm-redteam-core/runs
reward:
  toxicity_threshold: 0.5
